### ISSUE TITLE
Indexes issue after install app - MintHCM 3.0.8

### ISSUE THREAD

**Issue by aviniesky** [minthcm/minthcm#10]
Hello, 

I installed the app but after login to it I received various messages regarding "undefined indexes". Some examples are:
- Undefined index: LBL_NAV_DEFINITIONS in ....
- Undefined index: LBL_REPORT_LIST in...
- Undefined index: DMLocked index in...
- Undefined index: DMForced in...

(Attached image is included showing these messages)

![20210210_minthcm_indexes_issue](https://user-images.githubusercontent.com/9402278/107552901-da8daa00-6bb2-11eb-8d84-05a176756639.jpg)

I really apreciate if you can help me to resolve this issue.
If you need more information please don't hesitate to ask me.

Thank you. Regards.

**Comment by MintHCM-admin** [comment]
Of course, it is not property behavior for the system.
 You should change php settings. 
 Set  `display_errors = off`
After the change, please restart php server. 
We will add these settings to our installation instruction.

**Comment by summit1691** [comment]
After I turned off the error reporting the website just crashed with error
Fatal error: Uncaught Error: Call to undefined function mysqli_connect()
