### ISSUE TITLE
[Demo] Can't login

### ISSUE THREAD

**Issue by Volmarg** [minthcm/minthcm#11]
**Url**: 
- `https://demo.minthcm.cloud/index.php?module=Users&action=Login&login_language=en_us`

**Issue description**: Cannot login to the demo, go only an information. The demo user was generated like 1-2 min ago: 
- `You have been logged out because your session has expired.`

<b>Additionall Info</b>:
- screenshot:
![image](https://user-images.githubusercontent.com/37488679/107873240-63595e00-6eb1-11eb-9199-4649252433ca.png)

- tested in private mode: ain't working,
- browser info:
![image](https://user-images.githubusercontent.com/37488679/107873313-ee3a5880-6eb1-11eb-8ce0-49abdfffa7cf.png)

*Anyway I've found what I wanted from the code, so won't be retesting it after fix*

**Comment by MintHCM-admin** [comment]
Hello, thank you for noticing that. The demo is available again!
