### ISSUE TITLE
Error when install : Create default settings...

### ISSUE THREAD

**Issue by carinoz** [minthcm/minthcm#21]
on minthcm.log

Tue Jun 29 17:36:37 2021 [2232][-none-][FATAL] MysqliManager: Empty query
Tue Jun 29 17:36:47 2021 [2232][-none-][FATAL] Email address save error
<img width="463" alt="Screen Shot 2021-06-30 at 00 42 32" src="https://user-images.githubusercontent.com/5300406/123843428-1778f400-d93c-11eb-8ca9-0c7555ff4ca3.png">

**Comment by MintHCM-admin** [comment]
Hello,
Please, look into php.log and install.log. If you find something like that: "PHP Fatal error: Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv_substr() in /home/arthurk19/public_html/agilehr/vendor/symfony/polyfill-mbstring/Mbstring.php:568" then here you should find answer for this: https://stackoverflow.com/questions/42361270/how-to-fix-call-to-undefined-function-symfony-polyfill-mbstring-iconv-strpos-i

**Comment by SupersixEvo** [comment]
I'm getting stuck on the same part of installation but I can't find php.log or install.log in the folder MintHCM is unzipped into (nor anywhere else on the server).  Is there a process required to enable logging during installation?
