### ISSUE TITLE
Problem in new User field creation

### ISSUE THREAD

**Issue by dferraes** [minthcm/minthcm#25]
Hi,

I'm having issues to create new user field, after the clic on the add field button the system crash with an error 500 showed in the web browser console, in the web server the error that was displayed is:

PHP message: PHP Parse error:  syntax error, unexpected '<<' (T_SL), expecting ')' in /var/www/clients/client1/web11/web/modules/Tasks/metadata/subpanels/default.php on line 131\n', referer: https://xxxx.xxxxx.xxxxx/index.php?module=ModuleBuilder&action=index&type=studio

When i checked the file: modules/Tasks/metadata/subpanels/default.php there's some kind of version control code that i supouse its wrong, i deleted this code:

<<<<<<< HEAD
        'top_buttons' => array(
        array (
                         'widget_class'=>'SubPanelTopCreateButton',
                                ),
                        array (
                         'widget_class'=>'SubPanelTopSelectButton', 'popup_module' => 'Tasks'
                                ),
        ),

        'list_fields' => array(
                'object_image'=>array(
                        'vname' => 'LBL_OBJECT_IMAGE',
                        'widget_class' => 'SubPanelIcon',
                        'width' => '2%',
                ),
                'name'=>array(
                         'vname' => 'LBL_LIST_SUBJECT',
                         'widget_class' => 'SubPanelDetailViewLink',
                         'width' => '30%',
                ),
                'status'=>array(
                         'widget_class' => 'SubPanelActivitiesStatusField',
                         'vname' => 'LBL_LIST_STATUS',
                         'width' => '15%',
                ),
                'contact_name'=>array(
                         'widget_class' => 'SubPanelDetailViewLink',
                         'target_record_key' => 'contact_id',
                         'target_module' => 'Contacts',
                         'module' => 'Contacts',
                         'vname' => 'LBL_LIST_CONTACT',
                         'width' => '11%',
                ),
                'parent_name'=>array(
                         'vname' => 'LBL_LIST_RELATED_TO',
                         'width' => '22%',
                         'target_record_key' => 'parent_id',
                         'target_module_key'=>'parent_type',
                         'widget_class' => 'SubPanelDetailViewLink',
                         'sortable'=>false,
                ),
                'date_start' => array(
            'vname' => 'LBL_START_DATE',
            'width' => '10%',
        ),
                'date_modified'=>array(
                         'vname' => 'LBL_LIST_DATE_MODIFIED',
                         'width' => '10%',
                ),
                'edit_button'=>array(
                        'vname' => 'LBL_EDIT_BUTTON',
                         'widget_class' => 'SubPanelEditButton',
                         'width' => '2%',
                ),
                'remove_button'=>array(
                        'vname' => 'LBL_REMOVE',
                         'widget_class' => 'SubPanelRemoveButton',
                         'width' => '2%',
                ),
                'parent_id'=>array(
                        'usage'=>'query_only',
                ),
                'parent_type'=>array(
                        'usage'=>'query_only',
                ),
                'filename'=>array(
                        'usage'=>'query_only',
                        'force_exists'=>true
                        ),

        ),
);
=======

Now, the system works. How can i verify if this change is correct?

**Comment by MintHCM-admin** [comment]
Hello,
we found solution for you

<?php
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}
$subpanel_layout = array(
    'top_buttons' => array(
        array(
            'widget_class' => 'SubPanelTopCreateButton',
        ),
        array(
            'widget_class' => 'SubPanelTopSelectButton', 'popup_module' => 'Tasks',
        ),
    ),
    'list_fields' => array(
        'object_image' => array(
            'vname' => 'LBL_OBJECT_IMAGE',
            'widget_class' => 'SubPanelIcon',
            'width' => '2%',
        ),
        'name' => array(
            'vname' => 'LBL_LIST_SUBJECT',
            'widget_class' => 'SubPanelDetailViewLink',
            'width' => '30%',
        ),
        'status' => array(
            'widget_class' => 'SubPanelActivitiesStatusField',
            'vname' => 'LBL_LIST_STATUS',
            'width' => '15%',
        ),
        'contact_name' => array(
            'widget_class' => 'SubPanelDetailViewLink',
            'target_record_key' => 'contact_id',
            'target_module' => 'Contacts',
            'module' => 'Contacts',
            'vname' => 'LBL_LIST_CONTACT',
            'width' => '11%',
        ),
        'parent_name' => array(
            'vname' => 'LBL_LIST_RELATED_TO',
            'width' => '22%',
            'target_record_key' => 'parent_id',
            'target_module_key' => 'parent_type',
            'widget_class' => 'SubPanelDetailViewLink',
            'sortable' => false,
        ),
        'date_modified' => array(
            'vname' => 'LBL_LIST_DATE_MODIFIED',
            'width' => '10%',
        ),
        'assigned_user_name' => array(
            'name' => 'assigned_user_name',
            'vname' => 'LBL_ASSIGNED_TO_NAME',
            'widget_class' => 'SubPanelDetailViewLink',
            'target_record_key' => 'assigned_user_id',
            'target_module' => 'Users',
            'related_fields' => array(
                'assigned_user_id',
            ),
            'width' => '10%',
            'default' => true,
        ),
        'edit_button' => array(
            'vname' => 'LBL_EDIT_BUTTON',
            'widget_class' => 'SubPanelEditButton',
            'width' => '2%',
        ),
        'remove_button' => array(
            'vname' => 'LBL_REMOVE',
            'widget_class' => 'SubPanelRemoveButton',
            'width' => '2%',
        ),
        'parent_id' => array(
            'usage' => 'query_only',
        ),
        'parent_type' => array(
            'usage' => 'query_only',
        ),
        'filename' => array(
            'usage' => 'query_only',
            'force_exists' => true,
        ),
    ),
);

**Comment by MintHCM-admin** [comment]
Hello,
we found solution for you
```
<?php
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}
$subpanel_layout = array(
    'top_buttons' => array(
        array(
            'widget_class' => 'SubPanelTopCreateButton',
        ),
        array(
            'widget_class' => 'SubPanelTopSelectButton', 'popup_module' => 'Tasks',
        ),
    ),
    'list_fields' => array(
        'object_image' => array(
            'vname' => 'LBL_OBJECT_IMAGE',
            'widget_class' => 'SubPanelIcon',
            'width' => '2%',
        ),
        'name' => array(
            'vname' => 'LBL_LIST_SUBJECT',
            'widget_class' => 'SubPanelDetailViewLink',
            'width' => '30%',
        ),
        'status' => array(
            'widget_class' => 'SubPanelActivitiesStatusField',
            'vname' => 'LBL_LIST_STATUS',
            'width' => '15%',
        ),
        'contact_name' => array(
            'widget_class' => 'SubPanelDetailViewLink',
            'target_record_key' => 'contact_id',
            'target_module' => 'Contacts',
            'module' => 'Contacts',
            'vname' => 'LBL_LIST_CONTACT',
            'width' => '11%',
        ),
        'parent_name' => array(
            'vname' => 'LBL_LIST_RELATED_TO',
            'width' => '22%',
            'target_record_key' => 'parent_id',
            'target_module_key' => 'parent_type',
            'widget_class' => 'SubPanelDetailViewLink',
            'sortable' => false,
        ),
        'date_modified' => array(
            'vname' => 'LBL_LIST_DATE_MODIFIED',
            'width' => '10%',
        ),
        'assigned_user_name' => array(
            'name' => 'assigned_user_name',
            'vname' => 'LBL_ASSIGNED_TO_NAME',
            'widget_class' => 'SubPanelDetailViewLink',
            'target_record_key' => 'assigned_user_id',
            'target_module' => 'Users',
            'related_fields' => array(
                'assigned_user_id',
            ),
            'width' => '10%',
            'default' => true,
        ),
        'edit_button' => array(
            'vname' => 'LBL_EDIT_BUTTON',
            'widget_class' => 'SubPanelEditButton',
            'width' => '2%',
        ),
        'remove_button' => array(
            'vname' => 'LBL_REMOVE',
            'widget_class' => 'SubPanelRemoveButton',
            'width' => '2%',
        ),
        'parent_id' => array(
            'usage' => 'query_only',
        ),
        'parent_type' => array(
            'usage' => 'query_only',
        ),
        'filename' => array(
            'usage' => 'query_only',
            'force_exists' => true,
        ),
    ),
);
```

Best regards!
