### ISSUE TITLE
Installation Hangs on Database Creation

### ISSUE THREAD

**Issue by Bigben83** [minthcm/minthcm#5]
Hello I have been trying to install MINTHCM but its hanging on the `Create database...`

The Error log is showing the below  "MySQL error 1071: Specified key was too long; max key length is 1000 bytes"

`
Thu Oct 29 04:47:07 2020 [22224][-none-][FATAL] Mysqli_query failed.
Thu Oct 29 04:47:07 2020 [22224][-none-][FATAL] Error creating table: leads: Query Failed: CREATE TABLE leads (id char(36)  NOT NULL ,date_entered datetime  NULL ,date_modified datetime  NULL ,modified_user_id char(36)  NULL ,created_by char(36)  NULL ,description text  NULL ,deleted bool  DEFAULT '0' NULL ,assigned_user_id char(36)  NULL ,salutation varchar(255)  NULL ,first_name varchar(100)  NULL ,last_name varchar(100)  NULL ,title varchar(100)  NULL ,photo varchar(255)  NULL ,department varchar(100)  NULL ,do_not_call bool  DEFAULT '0' NULL ,phone_home varchar(100)  NULL ,phone_mobile varchar(100)  NULL ,phone_work varchar(100)  NULL ,phone_other varchar(100)  NULL ,phone_fax varchar(100)  NULL ,lawful_basis text(100)  NULL ,date_reviewed date  NULL ,lawful_basis_source varchar(100)  NULL ,primary_address_street varchar(150)  NULL ,primary_address_city varchar(100)  NULL ,primary_address_state varchar(100)  NULL ,primary_address_postalcode varchar(20)  NULL ,primary_address_country varchar(255)  NULL ,alt_address_street varchar(150)  NULL ,alt_address_city varchar(100)  NULL ,alt_address_state varchar(100)  NULL ,alt_address_postalcode varchar(20)  NULL ,alt_address_country varchar(255)  NULL ,assistant varchar(75)  NULL ,assistant_phone varchar(100)  NULL ,converted bool  DEFAULT '0' NULL ,refered_by varchar(100)  NULL ,lead_source varchar(100)  NULL ,lead_source_description text  NULL ,status varchar(100)  NULL ,status_description text  NULL ,reports_to_id char(36)  NULL ,account_name varchar(255)  NULL ,account_description text  NULL ,contact_id char(36)  NULL ,account_id char(36)  NULL ,opportunity_id char(36)  NULL ,opportunity_name varchar(255)  NULL ,opportunity_amount varchar(50)  NULL ,campaign_id char(36)  NULL ,birthdate date  NULL ,portal_name varchar(255)  NULL ,portal_app varchar(255)  NULL ,website varchar(255)  NULL  , PRIMARY KEY (id),   KEY idx_lead_acct_name_first (account_name, deleted),   KEY idx_lead_last_first (last_name, first_name, deleted),   KEY idx_lead_del_stat (last_name, status, deleted, first_name),   KEY idx_lead_opp_del (opportunity_id, deleted),   KEY idx_leads_acct_del (account_id, deleted),   KEY idx_del_user (deleted, assigned_user_id),   KEY idx_lead_assigned (assigned_user_id),   KEY idx_lead_contact (contact_id),   KEY idx_reports_to (reports_to_id),   KEY idx_lead_phone_work (phone_work),   KEY idx_leads_id_del (id, deleted)) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: MySQL error 1071: Specified key was too long; max key length is 1000 bytes
`

**Comment by MonilCereBulb** [comment]
I am facing the same issue as you are. Did you find any solution to this issue? @Bigben83

**Comment by monilshah98** [comment]
The above issue occurs due to MySQL storage engine. I solved the issue by changing the default storage engine of MySQL from the file `my.ini` which will be located in the installation directory of MySQL. 

Change the option `default-storage-engine=MYISAM` to `default-storage-engine=innodb`. 

Hope it helps. @Bigben83

**Comment by MintHCM-admin** [comment]
Thanks @monilshah98 for help. @Bigben83 do you still have the issue with the installation process? We do have this special guide for installation: https://minthcm.org/forums/forum/installing-minthcm/

**Comment by drbeanz** [comment]
the team not loading after install. The navigation is listedon the entire page not getting pass this

**Comment by drbeanz** [comment]
I meant theme

**Comment by drbeanz** [comment]
I follow the guide andnothing works in the last update....the first agreement page is blank also and database dont load all tables only 50 the took all night and yet not fully loaded
please check this update

**Comment by MichalNowacki** [comment]
Hi,
I agree the agreement page is blank.
Could you send more information about your environment? PHP version, MySQL version? I installed MintHCM without problems.

**Comment by sankethpb** [comment]
Hi,
Even my installation is stuck here at creating database. All system requirements are met as per Install Wizard.
![image](https://user-images.githubusercontent.com/16034868/102019573-5da0a880-3d9a-11eb-8252-891a85b08db6.png)

any help would be great.
Thank you

**Comment by sankethpb** [comment]
Mon Dec 14 04:22:49 2020 [32944][-none-][FATAL] Mysqli_query failed.
Mon Dec 14 04:22:49 2020 [32944][-none-][FATAL] Error creating table: fields_meta_data: Query Failed: CREATE TABLE fields_meta_data (id varchar(255)  NOT NULL ,name varchar(255)  NULL ,vname varchar(255)  NULL ,comments varchar(255)  NULL ,help varchar(255)  NULL ,custom_module varchar(255)  NULL ,type varchar(255)  NULL ,len int(11)  NULL ,required bool  DEFAULT '0' NULL ,default_value varchar(255)  NULL ,date_modified datetime  NULL ,deleted bool  DEFAULT '0' NULL ,audited bool  DEFAULT '0' NULL ,massupdate bool  DEFAULT '0' NULL ,duplicate_merge smallint  DEFAULT '0' NULL ,reportable bool  DEFAULT '1' NULL ,importable varchar(255)  NULL ,ext1 varchar(255)  NULL ,ext2 varchar(255)  NULL ,ext3 varchar(255)  NULL ,ext4 text  NULL  , PRIMARY KEY (id),   KEY idx_meta_id_del (id, deleted),   KEY idx_meta_cm_del (custom_module, deleted)) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: MySQL error 1071: Specified key was too long; max key length is 767 bytes

This is the error in minhcm.log

**Comment by erigglem** [comment]
Yea, this app is uninstallable in it's current form.

**Comment by MichalNowacki** [comment]
@sankethpb what is the version of your database? It is MySQL 5.6? Do you have possibilities to upgrade it to 5.7 version?

**Comment by RohitGalgali** [comment]
MySQL version : 8.0.25, php7.4. I have the same problem.

**Comment by RohitGalgali** [comment]
i have changed the PHP version to php7.1 and sql to 5.7. however, i have landed in another issue of cross reference request forgery which even after updating the config file in root doesnt solve the issue

**Comment by MintHCM-admin** [comment]
Hello Rohit, 

Please, look into php.log and install.log. If you find something like that: "PHP Fatal error: Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv_substr() in /home/arthurk19/public_html/agilehr/vendor/symfony/polyfill-mbstring/Mbstring.php:568" then here you should find answer for this: https://stackoverflow.com/questions/42361270/how-to-fix-call-to-undefined-function-symfony-polyfill-mbstring-iconv-strpos-i

**Comment by jontitmus-code** [comment]
Hi @MintHCM-admin,
Has there been any solution found to this?
I'm experiencing the same problem, with the installation getting stuck whilst creating Relationship Meta file files:

install.log (final excerpt, whole file attached)
`2023-07-17 15:48:09...creating Relationship Meta for Reactions
2023-07-17 15:48:09...processing table files
2023-07-17 15:48:09...creating table files
2023-07-17 15:48:09...creating Relationship Meta for Files`
[install.log](https://github.com/minthcm/minthcm/files/12072501/install.log)

minthcm.log
`Mon Jul 17 16:47:46 2023 [12][-none-][FATAL] MysqliManager: Empty query`


^^Not sure this is connected to the problem

Nothing of note in php_errors.log

Nothing of note in mysqld.log

Running ubuntu with Apache2, PHP 7.1, MySQL 5.7. Trying to install MintHCM 3.1.5

Many thanks

**Comment by MintHCM-admin** [comment]
Hi,

We've just installed MintHCM 3.1.5 on Apache/2.4.38, PHP 7.1.26, and MySQL 5.7.35-38 Percona Server. We didn't encounter any problems.

Have you tried to install it a second time?

Would you like to install Mint on a dedicated server? Alternatively, would using a Dockerfile be able to resolve the problem? We can provide the Dockerfile script.

**Comment by jontitmus-code** [comment]
If you're able to point me toward a dockerfile that would be great thank you.

**Comment by jontitmus-code** [comment]
@MintHCM-admin, just retried using percona/percona-server:5.7 over vanilla mysql:5.7, got stuck at the same place. 
Docker and compose file below:

**Comment by jontitmus-code** [comment]
@MintHCM-admin, worth adding that I've tried installing using the scripts above on ubuntu:latest as well as ubuntu:22.04 (LTS), with no improvement.

**Comment by MintHCM-admin** [comment]
Hello, we have simplified the docker-compose configuration to make debugging easier. Following the MintHCM installation guide (https://wiki.minthcm.org/index.php?title=Process:Installation_guide), we successfully installed MintHCM with just one change - increasing the upload_max_filesize limit to 10MB.

We've attached the modified  Docker directory,  which includes docker-compose.yml, Dockerfile, and the necessary directories

Tip: we used the container name 'mysql_hcm' to establish the connection to the MySQL database during the installation of MintHCM.

Give it a try with these changes, and you should be able to get MintHCM up and running smoothly on Docker. If you encounter any issues or have questions, feel free to ask.
[issue_5 (1).tar.gz](https://github.com/minthcm/minthcm/files/12159711/issue_5.1.tar.gz)

**Comment by jontitmus-code** [comment]
Thanks @MintHCM-admin, aside from the port mappings, I'm not really sure what the difference is between your dockerfiles and my own, yes there are a number of volume mappings missing, but unless I've seriously messed up my php.ini file, I'm stumped to be honest. Anyway, all up and running, I'll worry about my previous config another day 😆  Many thanks again!

**Comment by jontitmus-code** [comment]
@MintHCM-admin, found my issue - it was in the apache config - not sure what I'd done, but all sorted now.
