### ISSUE TITLE
Support for PHP > 7.1

### ISSUE THREAD

**Issue by riiwjohnson** [minthcm/minthcm#54]
Given that 7.1 went EOL on 2019-12-01, and now 7.4 is EOL as of 2022-11-28.  Are there any plans of bringing minthcm up to a supported  release?

**Comment by MintHCM-admin** [comment]
Hello!
Yes, we are planning to upgrade PHP in MintHCM. PHP 7.4 should be supported by the end of the first quoter of 2023. Then, PHP 8.1 would be supported by the end of the third quoter of 2023.

We will keep you informed here and on our forum when the PHP is upgrade up to PHP 7.4 and 8.1.
