### ISSUE TITLE
SAML + Keycloak

### ISSUE THREAD

**Issue by VincentSC** [minthcm/minthcm#56]
Today I managed to get SAML working with Keycloak. I had to make some changes to a few files, for which I can send a PR. I can also write some documentation.

Question. I noticed that it was not possible to create new users automatically, but with SuiteCRM 8.x it is. So what are the plans to upgrade to SuiteCRM 8.x?

**Comment by MintHCM-admin** [comment]
Hello,

Thank you for reaching out to us. We appreciate your interest in contributing to our project! We will be glad if you want to create PR :)

Regarding the issue you mentioned, it seems that users are not created automatically during login via SAML. If you use LDAP, the users are created, so you may be able to copy that part of the code.

As for upgrading to SuiteCRM8, we have decided not to do so. Instead, we are currently working on our own version of MintHCM4 with our own frontend application.

**Comment by VincentSC** [comment]
Was SAML removed from 4.0?
