### ISSUE TITLE
LDAP ducumentation

### ISSUE THREAD

**Issue by Uzzi** [minthcm/minthcm#6]
Hi, Where can I find LDAP support documentation?

I need LDAP users/group/OU particular configurations

Thank you
Regards

**Comment by MintHCM-admin** [comment]
Hi @Uzzi Try following these steps: [https://support.sugarcrm.com/Knowledge_Base/Password_Management/Configuring_LDAP_Authentication_Using_Active_Directory/](url) It should work!

**Comment by mahmutikilic** [comment]
@MintHCM-admin the document has been deleted. How can i find from your document? 
Because of there is any document for active directory, i can not set config for LDAP.
Can u help me?
