### ISSUE TITLE
Installation stuck on Database configuration

### ISSUE THREAD

**Issue by Cristian9828** [minthcm/minthcm#65]
Hello,
i'm trying to install but the system get stuck on this:

![image](https://github.com/minthcm/minthcm/assets/51407503/091e40d0-470e-40bb-8c13-4f2ade244d59)

PHP Version: 7.4.27 on Laragon

Tried to get install.log or minthcm.log but cant find any of these.
php.error is clean..

Let me know!
I'm very curious about using your program!

Thank you

**Comment by MintHCM-admin** [comment]
Hello! Have you tried the newest MintHCM v. 4.0.3? We released it last week. 

If the error still happens with the 4.0.3 then, please tell us which database you use and check if any errors are coming up in the browser console. It might provide some clues about what's going wrong. Let me know what you find, and we can troubleshoot from there.

**Comment by Cristian9828** [comment]
Hello!
I tried also with the newest 4.0.4 but nothing.
Tried to debug and found this:

![image](https://github.com/minthcm/minthcm/assets/51407503/01a1ce41-040f-4ead-a9f1-674c2c242afd)

Commenting the row containing "testConnection" function, it permits me to proceed.
With this, the installation stucks without telling me nothing.

So, I proceeded and the setup wizard came to this result:
![image](https://github.com/minthcm/minthcm/assets/51407503/546eff5c-abed-4fbb-b46a-15b4b4dc92d9)

Stuck on this, tried to refresh the page and I see:
![image](https://github.com/minthcm/minthcm/assets/51407503/5ee234e3-720e-4089-988d-021d64740f0b)

Looking at php.error log it tells me this error:

[04-Jun-2024 12:07:50 UTC] PHP Parse error:  syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in C:\laragon\www\minthcm\api\app\Controllers\GlobalSearchController.php on line 94

Now I'm trying to login but nothing happens.. It reloads and sends me again in login request.
This is all! Let me know if I can do something to resolve!

Thank you

**Comment by YesWeWeb** [comment]
Same here... with MariaDB 10

I tried to switch to PHP 8.0 instead of 7.4

Login page:
![image](https://github.com/minthcm/minthcm/assets/123606679/4448e2db-0750-4612-b339-ebea21fb1f35)

Installation :
![image](https://github.com/minthcm/minthcm/assets/123606679/9c9a086b-afc0-4935-a2b6-c356b3f0ac69)

**Comment by MintHCM-admin** [comment]
Hello YesWeWeb!
Could you please send us your PHP.log and screenshot of any errors in your browser's console?
