### ISSUE TITLE
Candidate stuck on "Saving" when adding data to profile

### ISSUE THREAD

**Issue by dustbro** [minthcm/minthcm#71]
I have created a Candidate. When I upload a PDF to the documents section of the candidate, the screen never gets past "saving". The file does actually upload because it's available when I refresh the page. This also happens when I create a Note. 

![Screenshot 2024-06-06 102340](https://github.com/minthcm/minthcm/assets/9417887/9bc4dc56-b753-4564-aaec-473c106e6f7d)

**Comment by MintHCM-admin** [comment]
Thank you for the information! We will look into this and release a potential fix in the next version.
