### ISSUE TITLE
Uploaded Files are not visible

### ISSUE THREAD

**Issue by dustbro** [minthcm/minthcm#72]
After a file has been uploaded to a candidate, the files are no longer viewable. The title bar of the Files section properly shows the amount of files. Clicking on the + sign to add more files does nothing.

![Screenshot 2024-06-06 112014](https://github.com/minthcm/minthcm/assets/9417887/89b51895-fc4e-4827-b878-a585376eaf2f)

**Comment by MintHCM-admin** [comment]
Please let us know which files you uploaded.
Could you send us a screenshot of the error from the browser console?
Also, could you send us the PHP logs and the Mint logs from the /legacy/minthcm.log directory?

**Comment by MintHCM-admin** [comment]
One of our developers tried to reproduce the bug. However, it works well on version 4.0.4.

I see you have the same version. Could you check that the new files/records are added to your database's "files" table? The parent_id and parent_type columns should be connected to your Candidate record.

Could you show the web browser console? There might be some related errors.

**Comment by dustbro** [comment]
Thanks for the reply. It seems to have been cured by updating ElasticSearch.
