### ISSUE TITLE
help!! forum issue ...

### ISSUE THREAD

**Issue by deehill** [minthcm/minthcm#73]
The minthcm  https://minthcm.org/support/ has the forum section...

However, I couldn't see a way to "post" I logged in, found the forum/topics.. and didn't see any process to create new posts.

Help would be appreciated.

thanks

I'm trying to figure when the app will run with PHP 8.2. Got a 8.2 server that I'd like to check the app out on.

thanks again..

**Comment by MintHCM-admin** [comment]
Hi! Did you scroll all the way to the end?

![Clipboard - June 25, 2024 9_17 (1)](https://github.com/minthcm/minthcm/assets/51930758/99113073-3aac-4272-96de-63f545327442)

**Comment by MintHCM-admin** [comment]
For now, MintHCM is not upgraded to PHP 8.2. We plan to upgrade it in Q3.

**Comment by deehill** [comment]
I never saw this part of the site/page..

How does one get there after logging in.

I can see the forum with "posts". Even tried running on a diff
browser/system.

thanks
