### ISSUE TITLE
The installation page does not open

### ISSUE THREAD

**Issue by SerhiiZahuba** [minthcm/minthcm#74]
Hello. 
Debian 12\ Centos7
PHP 8
Downloaded your script to the folder, configured the server (nginx), when I try to enter the site, I immediately get the authorization page instead of the installation page, when I try to manually go to the installation page, I see a 404 error. I looked in the directory, all the files in there are folders. Problem on different hosts with different OS. How to fix it?

Thanks

**Comment by MintHCM-admin** [comment]
Hello! We don't support Nginx, only Apache2. Please, check the requirements here: https://wiki.minthcm.org/index.php?title=Process:Installation_guide

**Comment by SerhiiZahuba** [comment]
Ok. Thanks
