### ISSUE TITLE
docker installation does not work

### ISSUE THREAD

**Issue by SerhiiZahuba** [minthcm/minthcm#75]
I tried to install your product via docker-compose - the first time it started fine but after I did docker-compose down 
docker-compose up -d The system is down. If you go to the container, the file folder www is empty.

![image](https://github.com/minthcm/minthcm/assets/36307887/fa0e770a-3571-4937-a644-77430cb69a08)

![image](https://github.com/minthcm/minthcm/assets/36307887/376a1bdd-587f-4db5-b42a-ef0241170ad1)

**Comment by MintHCM-admin** [comment]
Please check if the file /var/www/html/.initialized exists (it's a hidden file, so please use ls -lah). If it does, MintHCM will not start the installation after docker compose up -d but will only start services like Apache2 and cron. If you want to install MintHCM again, please remove this file.

Additionally, note that docker compose down does not delete volumes from the project by default. To remove the volumes, use the --volumes option.
