### ISSUE TITLE
Unable to Schedule Meetings Related to Specific Modules

### ISSUE THREAD

**Issue by SM-7603** [minthcm/minthcm#76]
### Description:

Hello,

I am encountering an issue while trying to schedule meetings. When attempting to relate a meeting to certain modules (Contracts, Invoices, Quotes, Products), I receive the following warning:

"**Warning: You do not have permission to access this module.**"

I have attached screenshots that show the issue when selecting these modules from the "Related to" dropdown list and a screenshot showing that I can view the contracts from the sidebar.

### Steps to Reproduce:

1. Go to the "Meetings" module.
2. Click on "Schedule Meeting".
3. Fill in the necessary meeting details.
4. From the "Related to" dropdown list, select one of the following modules: Contracts, Invoices, Quotes, Products.
5. Click the pointer button below the dropdown list. This should open a window where available items from the selected module can be chosen (e.g., selecting "Contracts" and hitting the pointer button should open a list of available contracts to select from).
6. The warning message appears immediately after clicking the pointer button, preventing any further actions.

### Expected Behavior:

The pointer button should open a window displaying available items from the selected module, and the meeting should be saved without any permission issues, correctly related to the selected module.

### Actual Behavior:

A warning message appears immediately after clicking the pointer button, stating that I do not have permission to access the selected module, preventing any further actions.

### Screenshots:

![permission-issues](https://github.com/user-attachments/assets/e13e852c-9233-4e94-8802-9e7873316281) Trying to schedule a meeting related to the "Contracts" module

![module-access-warning](https://github.com/user-attachments/assets/86d6d4f2-89fa-4b03-b862-06fed0f485a4) The warning message after selecting "Contracts"

![module-accessible-from-sidebar](https://github.com/user-attachments/assets/056290e9-310c-46cc-8add-925f04f45b89) Viewing contracts from the sidebar, demonstrating access to the module

### Additional Information:

- I have tried to replicate the issue in both a local environment and the Docker environment, but I have been getting the same results.
- I am logged in as the default administrator user, and I should have all the necessary permissions.
- I can view the contracts when I select the Contracts module from the sidebar menu, indicating that I do have access to the modules. However, I get the "**no permission**" warning when I try to create a meeting related to these modules.

Could you please advise on how to resolve this issue? If additional information is needed, please let me know.

Thank you for your help!

**Comment by MintHCM-admin** [comment]
Hello! Yesterday we released MintHCM 4.0.5. This problem is solved in the new version. Please, try with the latest version and let us know!
