### ISSUE TITLE
Unable to install mint using MintCLI

### ISSUE THREAD

**Issue by kemboi22** [minthcm/minthcm#77]
I am trying to install mint using mintHCM am getting an error
i dont know if its the elastic connection or
And is elastic search a must for mint to work

**Comment by kemboi22** [comment]
![Screenshot from 2024-07-27 02-33-36](https://github.com/user-attachments/assets/92169979-672b-4810-92ab-90d5de1f9575)

I am getting this error any help

**Comment by MintHCM-admin** [comment]
Hello, we have installed the MintHCM using MintCLI without any problems. 

What kind of PHP version do you have?
We think, that there can be problems with your PHP setting. You should enable the curl. 
There is an article on how to do it. Let us know if it helped: https://enginetemplates.com/call-to-undefined-function-curl_init/

**Comment by kemboi22** [comment]
am using php8.3 and also tried php7.4

**Comment by MintHCM-admin** [comment]
We recommend using PHP 8.0, PHP 8.3 is not supported. Have you tried to enable the curl by following the article?

**Comment by kemboi22** [comment]
![Screenshot from 2024-07-29 15-58-17](https://github.com/user-attachments/assets/0cde4c2e-fca8-4d2b-8583-7bc97bc38145)

i installed php curl and it worked
but now i get this error 
i am using podman containers to run the services how can i resolve this

**Comment by kemboi22** [comment]
so i should run mint before elastic search
